default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: clinica_api_development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: clinica_api_test
  host: localhost
  username: postgres
  password: postgres

production:
  <<: *default
  database: clinica_api_production
  username: clinica_api
  password: <%= ENV['CLINICA_API_DATABASE_PASSWORD'] %>
